"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from datetime import timedelta
from dotenv import load_dotenv

# Carrega as variáveis de ambiente do arquivo .env (se existir localmente)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-42dy5x5*8$(lede2&5lu4-5_+^#-p7xj&rne)x)rc8m7u(!*2z')

# SECURITY WARNING: don't run with debug turned on in production!
# Se DEBUG for True na variável, ele ativa. Caso contrário, False (seguro para produção).
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Permite todos os hosts por padrão em desenvolvimento, e pega do Render na produção
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', # Ajuda os estáticos em dev
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.matches',
    'apps.bets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Middleware para arquivos estáticos no Render
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# Em produção (Render), usa a DATABASE_URL. Local, usa sqlite3.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Se estivermos usando MySQL (como no Aiven) via variável de ambiente
db_url = os.environ.get('DATABASE_URL')
if db_url and db_url.startswith('mysql'):
    # Aiven MySQL requer SSL, mas o pymysql precisa do dicionário 'OPTIONS'
    DATABASES['default']['OPTIONS'] = {
        'ssl': {'ca': ''} # Diz ao pymysql para usar SSL, confiando no certificado fornecido
    }
    # Removemos o ssl-mode problemático do dicionário caso o dj_database_url o tenha adicionado
    if 'ssl-mode' in DATABASES['default'].get('OPTIONS', {}):
        del DATABASES['default']['OPTIONS']['ssl-mode']
    if 'ssl-mode' in DATABASES['default']:
        del DATABASES['default']['ssl-mode']

# Configuração para usar o PyMySQL se for MySQL
import pymysql
pymysql.install_as_MySQLdb()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Compressão e cache de arquivos estáticos no Render
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Permite requisições de qualquer origem, ótimo para quando o Vercel entrar
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    # O token de acesso dura 1 dia (ideal para um bolão)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    # O token de renovação dura 7 dias
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}