# Generated by Django 5.2.15 on 2026-06-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(verbose_name='Palpite Gols Casa')),
                ('away_score', models.PositiveIntegerField(verbose_name='Palpite Gols Fora')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Pontos Ganhos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='matches.match', verbose_name='Partida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Palpite',
                'verbose_name_plural': 'Palpites',
                'unique_together': {('user', 'match')},
            },
        ),
    ]
