# Generated by Django 5.2.15 on 2026-06-25 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_userprofile_current_points_and_more'),
        ('matches', '0002_bolao_match_penalty_winner_match_phase_match_bolao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='penalty_winner',
            field=models.ForeignKey(blank=True, help_text='Só preenchido quando o palpite é empate no mata-mata', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.team', verbose_name='Classificado nos Pênaltis'),
        ),
        migrations.CreateModel(
            name='BolaoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmou Participação')),
                ('previous_position', models.IntegerField(default=0, verbose_name='Posição Anterior')),
                ('current_position', models.IntegerField(default=0, verbose_name='Posição Atual')),
                ('previous_points', models.IntegerField(default=0, verbose_name='Pontos Anteriores')),
                ('current_points', models.IntegerField(default=0, verbose_name='Pontos Atuais')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.bolao', verbose_name='Bolão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolao_participations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participante do Bolão',
                'verbose_name_plural': 'Participantes do Bolão',
                'unique_together': {('bolao', 'user')},
            },
        ),
    ]
