# Generated by Django 5.2.15 on 2026-06-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Seleção')),
                ('group', models.CharField(help_text='Ex: A, B, C...', max_length=1, verbose_name='Grupo')),
                ('flag_url', models.URLField(blank=True, null=True, verbose_name='URL da Bandeira')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Gols Casa')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Gols Fora')),
                ('match_date', models.DateTimeField(verbose_name='Data e Hora do Jogo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('FINISHED', 'Finalizado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team', verbose_name='Time Fora')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team', verbose_name='Time Casa')),
            ],
        ),
    ]
