# Generated by Django 5.2.15 on 2026-06-25 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Bolão')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto para palpites'), ('LOCKED', 'Trancado (jogos em andamento)'), ('FINISHED', 'Encerrado')], default='OPEN', max_length=20, verbose_name='Status')),
                ('scoring_mode', models.CharField(choices=[('STANDARD', 'Padrão (5/3/0)'), ('KNOCKOUT', 'Mata-Mata (8/5/3/0 com pênaltis)')], default='STANDARD', max_length=20, verbose_name='Modo de Pontuação')),
                ('is_active', models.BooleanField(default=False, help_text='Qual bolão aparece por padrão no frontend', verbose_name='Bolão Ativo')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='Permitir Inscrições')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bolão',
                'verbose_name_plural': 'Bolões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_wins', to='matches.team', verbose_name='Classificado nos Pênaltis'),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(blank=True, default='', help_text='Ex: GROUP_STAGE, ROUND_16, QUARTER_FINALS...', max_length=30, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='match',
            name='bolao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.bolao', verbose_name='Bolão'),
        ),
    ]
