# Generated by Django 5.2.15 on 2026-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_bolaocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(blank=True, help_text='Ex: 73, 74, 75...', null=True, verbose_name='Número do Jogo (FIFA)'),
        ),
    ]
