# Generated by Django 5.2.15 on 2026-06-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalty_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gols Fora (Pênaltis)'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalty_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gols Casa (Pênaltis)'),
        ),
        migrations.AlterField(
            model_name='bolao',
            name='scoring_mode',
            field=models.CharField(choices=[('STANDARD', 'Padrão (5/3/0)'), ('KNOCKOUT', 'Mata-Mata (5/3/0 sem pênaltis)')], default='STANDARD', max_length=20, verbose_name='Modo de Pontuação'),
        ),
    ]
